company/company/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('user/', include('users.urls')),
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/products/urls.py
from django.urls import path
from . import views
from .views import GeneratePdf

urlpatterns = [
    path('',views.allProducts),
    # path('create', views.createProduct),
    path('view/<int:id>', views.viewProduct),
    # path('update/<int:id>', views.updateProduct),
    # path('addStock/', views.addProductStock),
    # path('delete/<int:id>', views.deleteProduct),
    path('export-in-excel', views.export_products, name="excel-export"),
    path('export-pdf', GeneratePdf.as_view(), name="pdf-export"),
    path('send-attachment-mail', views.send_email_with_attachment, name="send-attachment-mail"),
    path('load-api-data', views.api_data, name="load-api-data"),
    path('read-excel', views.read_excel, name="read-excel"),

    path('checkout', views.checkout),


    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item-increment-decrement',views.itemIncrementDecrement, name='itemIncrementDecrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
]

company/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views as user_views


urlpatterns = [
    path('', user_views.home, name='home'),
    path('signup', user_views.register, name='signup'),
    path('login', user_views.login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

company/products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "category"


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    price = models.FloatField(default=0.00)
    code = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images/')
    unit_in_stock = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "product"


class Customer(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=50)
    point = models.IntegerField(default=0)
    member_label = models.CharField(max_length=20, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "customer"


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    shipping_address = models.CharField(max_length=300)
    order_amount = models.FloatField(default=0)
    shipping_charge = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    total_amount = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.shipping_address

    class Meta:
        db_table = "order"


class OrderDetails(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    unit_price = models.EmailField(max_length=50)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "order_details"

company/products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

company/products/views.py
from django.shortcuts import render, redirect, HttpResponse
from products.forms import ProductForm
from products.models import Product, Category, Customer, Order, OrderDetails
from django.db.models.functions import Lower
from django.db.models import Q, F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.cart import Cart
from django.http.response import JsonResponse
import json
import xlwt
from datetime import datetime
from .export_pdf import html_to_pdf
from django.template.loader import render_to_string
from django.views.generic import View
from django.core.mail import EmailMessage
import requests
import pandas as pd
from django.core.files.storage import FileSystemStorage


def allProducts(request):
  
    searchText = request.GET.get('search')
    sortText = request.GET.get('sort')

    if(searchText):
        products = Product.objects.annotate(
            name_lower=Lower('name'),
            cat_name_lower=Lower('category__name')
        ).filter(
            Q(name_lower__icontains=searchText.lower())
            | Q(cat_name_lower__icontains=searchText.lower())
            | Q(code__icontains=searchText)
        )
    elif(sortText):
        products = Product.objects.all().order_by(sortText)
    else:
        products = Product.objects.all()

    if(searchText == None):
        searchText = ''
    if(sortText == None):
        sortText = ''

    page = request.GET.get('page', 1)

    paginator = Paginator(products, 5)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    cartSession = request.session.get('cart')
    cartItems = list(cartSession.values())
    cartIds = []
    for c in cartItems :
        cartIds.append(c['product_id'])

    return render(request,"product_list.html", {'products':data, 'carts':cartIds, 'search':searchText, 'sort':sortText})


# def createProduct(request):
#     category = Category.objects.all()

#     if request.method == "POST":
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect('/')
#             except:
#                 pass
#     else:
#         form = ProductForm()
    
#     return render(request,'product_create.html', {'form':form, 'category': category})


def viewProduct(request, id):
    product = Product.objects.get(id=id)
    return render(request,'product_view.html', {'product':product})


# def updateProduct(request, id):
#     product = Product.objects.get(id=id)
#     category = Category.objects.all()

#     if request.method == "POST":
#         form = ProductForm(request.POST, request.FILES, instance = product)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect("/")
#             except:
#                 pass

#     return render(request, 'product_edit.html', {'product':product, 'category': category})


# def addProductStock(request):
#     productId = request.POST.get('product_id')
#     stock=request.POST.get('new_stock')

#     Product.objects.filter(id=productId).update(stock=F('stock')+int(stock))
#     return redirect("/product")


# def deleteProduct(request, id):
#     product = Product.objects.get(id=id)
#     product.delete()
#     return redirect("/product")


def checkout(request):
    cartSession = request.session.get('cart')
    cartItems = list(cartSession.values())

    data = []
    orderAmount = 0
    shippingCharge = 0
    discount = 0

    for c in cartItems :
        product = Product.objects.get(id=c['product_id'])
        data.append({'product': product, 'quantity': c['quantity']})

        orderAmount += (product.price * c['quantity'])
        
    if request.method == "POST":
        customer_name = request.POST.get('name')
        customer_email = request.POST.get('email')
        customer_phone = request.POST.get('phone')
        shipping_address = request.POST.get('address')

        currentCustomer = Customer.objects.filter(phone=customer_phone).first()

        if(currentCustomer == None):
            cId = Customer.objects.create(
                name=customer_name,
                email=customer_email,
                phone=customer_phone,
            )
            
            currentCustomer = Customer.objects.filter(phone=customer_phone).first()
        else:
            cId = currentCustomer.id

        orderId = Order.objects.create(
            customer=currentCustomer,
            order_amount=orderAmount,
            shipping_charge=shippingCharge,
            discount=discount,
            total_amount=(orderAmount+shippingCharge)-discount,
            shipping_address=shipping_address,
        )

        for item in data:
            OrderDetails.objects.create(
                order=orderId,
                product=item['product'],
                unit_price=item['product'].price,
                quantity=item['quantity'],
            )
            Product.objects.filter(id=item['product'].id).update(unit_in_stock=F('unit_in_stock')-int(item['quantity']))

        cart_clear(request)

        point = currentCustomer.point+(orderAmount/100)
        memberLabel = ""
        
        if point > 1000:
            memberLabel = "VIP Member"
        elif point > 500:
            memberLabel = "Gold Member"
        elif point > 0:
            memberLabel = "Silver Member"
        else:
            memberLabel = "Member"

        Customer.objects.filter(id=currentCustomer.id).update(point=point, member_label=memberLabel)

        return redirect("/")
    else:
        return render(request, 'checkout.html', {'products':data, 'total_price': orderAmount})


def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    
    cartSession = request.session.get('cart')
    cartItems = list(cartSession.values())
    
    foundInCart = False

    for c in cartItems :
        if c['product_id'] == id and (c['quantity']) < product.unit_in_stock:
            foundInCart = True
            cart.add(product=product)

    if(foundInCart == False and product.unit_in_stock > 0):
        cart.add(product=product)


    return redirect("/")

def itemIncrementDecrement(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        productId = request.GET.get('product_id')
        status = request.GET.get('status')

        cart = Cart(request)
        product = Product.objects.get(id=productId)
        cartSession = request.session.get('cart')
        cartItems = list(cartSession.values())

        if status == 'plus':
            notFound = True

            for c in cartItems :
                if c['product_id'] == product.id and (c['quantity']) < product.unit_in_stock:
                    notFound = False
                    cart.add(product=product)

            if notFound:
                cart.add(product=product)

        elif status == 'minus':
            found = False

            for c in cartItems :
                if c['product_id'] == product.id and (c['quantity']) > 1:
                    found = True
                    cart.decrement(product=product)

                    
            if found == False:
                item_clear(request, product.id)

        elif status == 'remove':
            item_clear(request, product.id)

        cartSession = request.session.get('cart')
        cartItems = list(cartSession.values())

        orderAmount = 0
        shippingCharge = 0
        discount = 0
        qty = 0

        for c in cartItems :
            product = Product.objects.get(id=c['product_id'])
            orderAmount += (product.price * c['quantity'])

            if int(productId) == int(c['product_id']):
                qty = c['quantity']

        data = {
            'quantity': qty,
            'order_amount': orderAmount,
            'shipping_charge': shippingCharge,
            'discount': discount,
            'total_price': (orderAmount+shippingCharge)-discount,
        }
        dump = json.dumps(data)

        return JsonResponse(dump, safe=False)
    else:
        pass
    
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("/")

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("/")


def export_products(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="products.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    
    styleTitle = xlwt.easyxf('font: name Calibri, height 360, bold on, colour_index black; align: wrap on, vert center, horiz center; border : bottom thin, right thin, top thin, left thin;')
    styleColumnTitle = xlwt.easyxf('font: name Calibri, height 280, bold on; align: wrap on, vert center, horiz center; ')
    styleName = xlwt.easyxf('font: name Calibri, height 280, color-index green, bold on; align: wrap on, vert center, horiz left; ')
    styleId = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    styleCategoryName = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    stylePrice = xlwt.easyxf('font: name Calibri, height 280, bold on; align: wrap on, vert center, horiz right; ', num_format_str='#,##0.00')
    styleStock = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    styleCode = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    styleCreated = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')

company/products/templates/api_view.html
{% extends 'main.html' %}

{% comment %} {% load static %} {% endcomment %}

{% block title %}
    API Data List
{% endblock title %}

{% block style %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
{% endblock style %}

{% block content %}
    <div class="container">
        </br>
        <div class="text-center">
            <div class="col-sm-12">
                <h3>API Data</h3>
            </div>
        </div>
        </br>

        <table class="table table-bordered table-sm">
            <thead >
                <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">Title</th>
                    <th class="text-center">Body</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td class="text-center align-middle">{{ post.id }}</td>
                        <td class="align-middle">{{ post.title }}</td>
                        <td class="text-justify align-middle">{{ post.body }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if posts.has_other_pages %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end mr-3">
                <li class="page-item {% if posts.has_previous %} {% else %}disabled{% endif %}"><a class="page-link" href="{% if posts.has_previous %}?page={{ posts.previous_page_number }}{% endif %}">Previous</a></li>

                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item active text-white"><a class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if posts.has_next %} {% else %}disabled{% endif %}"><a class="page-link" href="{% if posts.has_next %}?page={{ posts.next_page_number }}{% endif %}">Next</a></li>
            </ul>
        </nav>
    {% endif %}
    </div>
{% endblock content %}

company/products/templates/checkout.html
{% extends 'main.html' %}
{% comment %} {% load static %} {% endcomment %}

{% block title %}
    Check Out
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
{% endblock style %}

{% block content %}
    </br>
    <div class="container">
        <table class="table table-bordered table-sm">
            <thead >
                <tr>
                    <th class="text-center">Image</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Category</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Stock</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr class="cart-data-{{product.product.id}}">
                        <td class="text-center align-middle" style="height: 100px;">
                            <a href={{ product.product.image.url }} target="_blank">
                                <img src={{ product.product.image.url }} class="img-responsive mh-100" alt={{ product.product.name }}/>
                            </a>
                        </td>
                        <td class="text-left align-middle">{{ product.product.name }}</td>
                        <td class="text-center align-middle">{{ product.product.category.name }}</td>
                        <td class="text-center align-middle">{{ product.product.price }}</td>
                        <td class="text-center align-middle">{{ product.product.unit_in_stock }}</td>
                        <td class="text-center align-middle">
                            <a class="btn btn-info text-white btn-sm" onclick="cartIncrementDecrement('{{ product.product.id }}', 'minus')">
                                <span class="glyphicon glyphicon-pencil">-</span>
                            </a>
                            <span class='mr-2 ml-2' id='quantityCount_{{product.product.id}}'>
                                {{product.quantity}}
                            </span>
                            <a class="btn btn-info text-white btn-sm" onclick="cartIncrementDecrement('{{ product.product.id }}', 'plus')">
                                <span class="glyphicon glyphicon-pencil">+</span>
                            </a>
                            <br>
                            <br>
                            <a class="btn btn-danger text-white btn-sm" onclick="cartIncrementDecrement('{{ product.product.id }}', 'remove')">
                                <span class="glyphicon glyphicon-pencil">REMOVE</span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h3 class="text-right"> Total Price: <span id="totalPrice">{{ total_price }}</span> </h3>
        <br><br><br><br>
        <form method="POST" class="post-form">
            {% csrf_token %}
            <div>
                <div class="form-group text-center">
                    <div class="col-sm-12">
                        <h3>Order Information</h3>
                    </div>
                </div>
                <br>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Name:</label>
                    <div class="col-sm-9">
                        <input class="form-control" type="text" name="name" id="id_name" required maxlength="100" value="" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Phone:</label>
                    <div class="col-sm-9">
                        <input class="form-control" type="text" name="phone" id="id_phone" required maxlength="20" value=""/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Email:</label>
                    <div class="col-sm-9">
                        <input class="form-control" type="text" name="email" id="id_email" required maxlength="50" value="" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Adderss:</label>
                    <div class="col-sm-9">
                        <input class="form-control" type="text" name="address" id="id_address" required maxlength="250" value="" />
                    </div>
                </div>
                
                <div class="form-group text-center">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-success">Submit Order</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
    <script>       
        function cartIncrementDecrement(id, status){
            var url = "/cart/item-increment-decrement"; 

            $.ajax({
                url: url,
                type:'GET',
                data:{
                    product_id : id, 
                    status: status,
                },
                success: function(data){
                    var returnedData = JSON.parse(data);
                    
                    $('#totalPrice').html(returnedData['total_price'])
                    $('#quantityCount_'+id).html(returnedData['quantity'])

                    if(status == 'remove' && returnedData['quantity'] == 0){
                        document.querySelector('.cart-data-'+id).style.display = 'none';
                    }
                },
                error: function(data){},
            })
        }
    </script>
{% endblock %}

company/products/templates/excel_read_data.html
{% extends 'main.html' %}

{% comment %} {% load static %} {% endcomment %}

{% block title %}
    API Data List
{% endblock title %}

{% block style %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
{% endblock style %}

{% block content %}
    <div class="mr-3 ml-3">
        </br>
        <div class="text-center">
            <div class="col-sm-12">
                <h3>Excel Data</h3>
            </div>
        </div>
        </br>

        <table class="table table-bordered table-sm">
            <thead >
                <tr>
                    {% for head in header %}

                        <th class="text-center">{{ head }}</th>

                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for obj in data %}
                    <tr>
                        {% for de in obj %}
                            <td class="text-center align-middle">{{ de }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

company/products/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} {% endblock title %}</title>

        <link rel="stylesheet" href="{% static 'style.css' %}">

        {% block style %}
        {% endblock style %}
    </head>
    
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

company/products/templates/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products PDF</title>
    <style>
        h1 {
          text-align: center;
        }
        td, th {
          text-align: center;
        }
        
    </style>
</head>
<body>
    
      <h1>List of Products</h1>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Stock</th>
            <th>Code</th>
            <th>Price</th>
            <th>Image</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.name }}</td>
                <td>{{ product.category.name }}</td>
                <td>{{ product.unit_in_stock }}</td>
                <td>{{ product.code }}</td>
                <td>{{ product.price }}</td>
                <td class="text-center align-middle" style="height: 70px;" >
                    <img src="{{ base_url }}/{{ product.image.url }}" class="img-responsive mh-100" alt={{ product.name }}/>
                </td>
            </tr>
          {% endfor %}    
        </tbody>
      </table>
</body>
</html>

company/products/templates/product_view.html
{% extends 'main.html' %}

{% comment %} {% load static %} {% endcomment %}

{% block title %}
    Product Details
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock style %}

{% block content %}
    <form method="POST" class="post-form" action="/product/update/{{product.id}}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <br>
            <br>
            <div class="form-group text-center">
                <div class="col-sm-12">
                    <h3>Product Details</h3>
                </div>
            </div>
            <br>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">ID:</label>
                <div class="col-sm-9">
                    <label class="col-form-label">{{ product.name }}</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Name:</label>
                <div class="col-sm-9">
                    <label class="col-form-label">{{ product.name }}</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Price:</label>
                <div class="col-sm-9">
                    <label class="col-form-label">{{ product.price }}</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Stock:</label>
                <div class="col-sm-9">
                    <label class="col-form-label">{{ product.unit_in_stock }}</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Code:</label>
                <div class="col-sm-9">
                    <label class="col-form-label">{{ product.code }}</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Category:</label>
                <div class="col-sm-9">
                    <label class="col-form-label">{{ product.category.name }}</label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Image:</label>
                <div class="col-sm-9" style="height: 200px;">
                    <a href={{ product.image.url }} target="_blank">
                        <img src="{{ product.image.url }}" class="img-responsive mh-100" alt="product.name"/>
                    </a>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}