company/company/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('user/', include('users.urls')),
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/products/urls.py
from django.urls import path
from . import views
from .views import GeneratePdf

urlpatterns = [
    path('',views.allProducts),
    # path('create', views.createProduct),
    path('view/<int:id>', views.viewProduct),
    # path('update/<int:id>', views.updateProduct),
    # path('addStock/', views.addProductStock),
    # path('delete/<int:id>', views.deleteProduct),
    path('export-in-excel', views.export_products, name="excel-export"),
    path('export-pdf', GeneratePdf.as_view(), name="pdf-export"),
    path('send-attachment-mail', views.send_email_with_attachment, name="send-attachment-mail"),
    path('load-api-data', views.api_data, name="load-api-data"),
    path('read-excel', views.read_excel, name="read-excel"),

    path('checkout', views.checkout),


    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item-increment-decrement',views.itemIncrementDecrement, name='itemIncrementDecrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
]

company/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views as user_views


urlpatterns = [
    path('', user_views.home, name='home'),
    path('signup', user_views.register, name='signup'),
    path('login', user_views.login, name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

company/products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "category"


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    price = models.FloatField(default=0.00)
    code = models.CharField(max_length=20)
    image = models.ImageField(upload_to='images/')
    unit_in_stock = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "product"


class Customer(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=50)
    point = models.IntegerField(default=0)
    member_label = models.CharField(max_length=20, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = "customer"


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    shipping_address = models.CharField(max_length=300)
    order_amount = models.FloatField(default=0)
    shipping_charge = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    total_amount = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.shipping_address

    class Meta:
        db_table = "order"


class OrderDetails(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    unit_price = models.EmailField(max_length=50)
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "order_details"

company/users/models.py
from django.db import models

# Create your models here.

company/products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

company/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

company/products/views.py
from django.shortcuts import render, redirect, HttpResponse
from products.forms import ProductForm
from products.models import Product, Category, Customer, Order, OrderDetails
from django.db.models.functions import Lower
from django.db.models import Q, F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.cart import Cart
from django.http.response import JsonResponse
import json
import xlwt
from datetime import datetime
from .export_pdf import html_to_pdf
from django.template.loader import render_to_string
from django.views.generic import View
from django.core.mail import EmailMessage
import requests
import pandas as pd
from django.core.files.storage import FileSystemStorage


def allProducts(request):
  
    searchText = request.GET.get('search')
    sortText = request.GET.get('sort')

    if(searchText):
        products = Product.objects.annotate(
            name_lower=Lower('name'),
            cat_name_lower=Lower('category__name')
        ).filter(
            Q(name_lower__icontains=searchText.lower())
            | Q(cat_name_lower__icontains=searchText.lower())
            | Q(code__icontains=searchText)
        )
    elif(sortText):
        products = Product.objects.all().order_by(sortText)
    else:
        products = Product.objects.all()

    if(searchText == None):
        searchText = ''
    if(sortText == None):
        sortText = ''

    page = request.GET.get('page', 1)

    paginator = Paginator(products, 5)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    cartSession = request.session.get('cart')
    cartItems = list(cartSession.values())
    cartIds = []
    for c in cartItems :
        cartIds.append(c['product_id'])

    return render(request,"product_list.html", {'products':data, 'carts':cartIds, 'search':searchText, 'sort':sortText})


# def createProduct(request):
#     category = Category.objects.all()

#     if request.method == "POST":
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect('/')
#             except:
#                 pass
#     else:
#         form = ProductForm()
    
#     return render(request,'product_create.html', {'form':form, 'category': category})


def viewProduct(request, id):
    product = Product.objects.get(id=id)
    return render(request,'product_view.html', {'product':product})


# def updateProduct(request, id):
#     product = Product.objects.get(id=id)
#     category = Category.objects.all()

#     if request.method == "POST":
#         form = ProductForm(request.POST, request.FILES, instance = product)
#         if form.is_valid():
#             try:
#                 form.save()
#                 return redirect("/")
#             except:
#                 pass

#     return render(request, 'product_edit.html', {'product':product, 'category': category})


# def addProductStock(request):
#     productId = request.POST.get('product_id')
#     stock=request.POST.get('new_stock')

#     Product.objects.filter(id=productId).update(stock=F('stock')+int(stock))
#     return redirect("/product")


# def deleteProduct(request, id):
#     product = Product.objects.get(id=id)
#     product.delete()
#     return redirect("/product")


def checkout(request):
    cartSession = request.session.get('cart')
    cartItems = list(cartSession.values())

    data = []
    orderAmount = 0
    shippingCharge = 0
    discount = 0

    for c in cartItems :
        product = Product.objects.get(id=c['product_id'])
        data.append({'product': product, 'quantity': c['quantity']})

        orderAmount += (product.price * c['quantity'])
        
    if request.method == "POST":
        customer_name = request.POST.get('name')
        customer_email = request.POST.get('email')
        customer_phone = request.POST.get('phone')
        shipping_address = request.POST.get('address')

        currentCustomer = Customer.objects.filter(phone=customer_phone).first()

        if(currentCustomer == None):
            cId = Customer.objects.create(
                name=customer_name,
                email=customer_email,
                phone=customer_phone,
            )
            
            currentCustomer = Customer.objects.filter(phone=customer_phone).first()
        else:
            cId = currentCustomer.id

        orderId = Order.objects.create(
            customer=currentCustomer,
            order_amount=orderAmount,
            shipping_charge=shippingCharge,
            discount=discount,
            total_amount=(orderAmount+shippingCharge)-discount,
            shipping_address=shipping_address,
        )

        for item in data:
            OrderDetails.objects.create(
                order=orderId,
                product=item['product'],
                unit_price=item['product'].price,
                quantity=item['quantity'],
            )
            Product.objects.filter(id=item['product'].id).update(unit_in_stock=F('unit_in_stock')-int(item['quantity']))

        cart_clear(request)

        point = currentCustomer.point+(orderAmount/100)
        memberLabel = ""
        
        if point > 1000:
            memberLabel = "VIP Member"
        elif point > 500:
            memberLabel = "Gold Member"
        elif point > 0:
            memberLabel = "Silver Member"
        else:
            memberLabel = "Member"

        Customer.objects.filter(id=currentCustomer.id).update(point=point, member_label=memberLabel)

        return redirect("/")
    else:
        return render(request, 'checkout.html', {'products':data, 'total_price': orderAmount})


def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    
    cartSession = request.session.get('cart')
    cartItems = list(cartSession.values())
    
    foundInCart = False

    for c in cartItems :
        if c['product_id'] == id and (c['quantity']) < product.unit_in_stock:
            foundInCart = True
            cart.add(product=product)

    if(foundInCart == False and product.unit_in_stock > 0):
        cart.add(product=product)


    return redirect("/")

def itemIncrementDecrement(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_ajax:
        productId = request.GET.get('product_id')
        status = request.GET.get('status')

        cart = Cart(request)
        product = Product.objects.get(id=productId)
        cartSession = request.session.get('cart')
        cartItems = list(cartSession.values())

        if status == 'plus':
            notFound = True

            for c in cartItems :
                if c['product_id'] == product.id and (c['quantity']) < product.unit_in_stock:
                    notFound = False
                    cart.add(product=product)

            if notFound:
                cart.add(product=product)

        elif status == 'minus':
            found = False

            for c in cartItems :
                if c['product_id'] == product.id and (c['quantity']) > 1:
                    found = True
                    cart.decrement(product=product)

                    
            if found == False:
                item_clear(request, product.id)

        elif status == 'remove':
            item_clear(request, product.id)

        cartSession = request.session.get('cart')
        cartItems = list(cartSession.values())

        orderAmount = 0
        shippingCharge = 0
        discount = 0
        qty = 0

        for c in cartItems :
            product = Product.objects.get(id=c['product_id'])
            orderAmount += (product.price * c['quantity'])

            if int(productId) == int(c['product_id']):
                qty = c['quantity']

        data = {
            'quantity': qty,
            'order_amount': orderAmount,
            'shipping_charge': shippingCharge,
            'discount': discount,
            'total_price': (orderAmount+shippingCharge)-discount,
        }
        dump = json.dumps(data)

        return JsonResponse(dump, safe=False)
    else:
        pass
    
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("/")

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("/")


def export_products(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="products.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    
    styleTitle = xlwt.easyxf('font: name Calibri, height 360, bold on, colour_index black; align: wrap on, vert center, horiz center; border : bottom thin, right thin, top thin, left thin;')
    styleColumnTitle = xlwt.easyxf('font: name Calibri, height 280, bold on; align: wrap on, vert center, horiz center; ')
    styleName = xlwt.easyxf('font: name Calibri, height 280, color-index green, bold on; align: wrap on, vert center, horiz left; ')
    styleId = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    styleCategoryName = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    stylePrice = xlwt.easyxf('font: name Calibri, height 280, bold on; align: wrap on, vert center, horiz right; ', num_format_str='#,##0.00')
    styleStock = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    styleCode = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')
    styleCreated = xlwt.easyxf('font: name Calibri, height 280; align: wrap on, vert center, horiz center; ')

company/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login

def home(request):
    if(request.user.is_authenticated):
        context = {'name': request.user.first_name+" "+request.user.last_name}
        return render(request, 'home.html', context)
    else:
        return redirect('login')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, f'Your account has been created. You can log in now!')    
            return redirect('login')
    else:
        form = UserRegistrationForm()

    context = {'form': form}
    return render(request, 'register.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        print(form.data)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                auth_login(request, user)
                messages.success(request, f'Successfully logged in')    
                return redirect('/')
            else:
                messages.error(request,"Invalid username or password.")
        
    else:
        form = AuthenticationForm()

    context = {'form': form}
    return render(request, 'login.html', context)

company/users/templates/products/product_create.html
{% extends 'main.html' %}

{% comment %} {% load static %} {% endcomment %}

{% block title %}
    Product Create
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock style %}

{% block content %}
    <form method="POST" class="post-form" action="create" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <br>
            <br>
            <div class="form-group text-center">
                <div class="col-sm-12">
                    <h3>Enter Product Details</h3>
                </div>
            </div>
            <br>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Name:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="name" id="id_name" required maxlength="100" value=
                    {% if form.name.value != null %}
                        {{form.name.value}}
                    {% else %}
                        ""
                    {% endif %}
                    />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Price:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="price" id="id_price" required maxlength="20" value=
                    {% if form.price.value != null %}
                        {{form.price.value}}
                    {% else %}
                        ""
                    {% endif %}
                    />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Code:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="code" id="id_code" required maxlength="15" value=
                    {% if form.code.value != null %}
                        {{form.code.value}}
                    {% else %}
                        ""
                    {% endif %}
                    />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Category:</label>
                <div class="col-sm-9">
                    <select class="form-control" name="category">
                        <option selected disabled>Select Category</option>
                        {% for cat in category %}
                            <option {% if cat.id == form.category.id %}selected{% endif %}
                            value="{{cat.id}}">{{cat.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Image:</label>
                <div class="col-sm-9">
                    <input type="file" name="image" id="id_image" accept="image/*" value=
                    {% if form.image != null %}
                        {{form.image.url}}
                    {% else %}
                        ""
                    {% endif %}
                    />
                </div>
            </div>
            </br> </br>
            <input type="hidden" name="unit_in_stock" id="id_unit_in_stock" value="0"/>
            <input type="hidden" name="unit_in_order" id="id_unit_in_stock" value="0"/>
            <div class="form-group text-center">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

company/users/templates/products/product_edit.html
{% extends 'main.html' %}

{% comment %} {% load static %} {% endcomment %}

{% block title %}
    Edit Product
{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock style %}

{% block content %}
    <form method="POST" class="post-form" action="/product/update/{{product.id}}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <br>
            <br>
            <div class="form-group text-center">
                <div class="col-sm-12">
                    <h3>Update Product Details</h3>
                </div>
            </div>
            <br>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Name:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="name" id="id_name" required maxlength="100" value="{{ product.name }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Price:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="price" id="id_price" required maxlength="20" value="{{ product.price }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Code:</label>
                <div class="col-sm-9">
                    <input class="form-control" type="text" name="code" id="id_code" required maxlength="15" value="{{ product.code }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Category:</label>
                <div class="col-sm-9">
                    <select class="form-control" name="category">
                        {% if product.category == null %}
                            <option selected disabled>Select Category</option>
                        {% endif %}
                        
                        {% for cat in category %}
                            <option 
                            {% if cat.id == product.category.id %}
                                selected
                            {% endif %}
                            value="{{cat.id}}">{{cat.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Image:</label>
                <div class="col-sm-9 col">
                    <label class="col">Current: <a href={{ product.image.url }} target="_blank">{{ product.image.name }}</a></label>
                    <input class="col" type="file" name="image" id="id_image" accept="image/*" value="{{ product.image.url }}" />
                </div>
            </div>
            </br> </br>
            <input type="hidden" name="stock" id="id_stock" value="{{ product.stock }}" />
            <input type="hidden" name="unit_in_stock" id="id_unit_in_stock" value="{{ product.unit_in_stock }}"/>
            <input type="hidden" name="unit_in_order" id="id_unit_in_stock" value="{{ product.unit_in_order }}"/>
            <div class="form-group text-center">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}